export type OperatingReference = {
  kind: 'SYSTEM LAB' | 'KERNEL API' | 'SDK' | 'MCP' | 'CONTRACT' | 'SOURCE' | 'NETWORK';
  label: string;
  value: string;
  href?: string;
};

export type OperatingModel = {
  fields: Array<[string, string]>;
  flow: Array<[string, string, 'runtime' | 'wallet' | 'network' | 'exception']>;
  failures: Array<[string, string, string]>;
  example: {
    title: string;
    context: string;
    steps: string[];
    result: string;
  };
  references: OperatingReference[];
};

const canonicalExample = {
  context: 'A Commerce Operator proposes a 420 orUSD RailsFlow with a 30 second lifespan inside Path 04. The Path ceiling is 1,000 orUSD and the execution sequence is lane 04.',
};

export const operatingModels: Record<string, OperatingModel> = {
  overview: {
    fields: [['Principal', 'The person or organisation that owns the economic activity.'], ['Authority', 'The signed Workspace and Path objects that define who may act and within which limits.'], ['Commitment', 'The Pact that freezes the accepted commercial terms.'], ['Evidence', 'Proof checkpoints and verified receipts that support state advancement.'], ['Settlement', 'RailsFlow, Paycard, Vault, and STN-Delta state that routes value.'], ['Resolution', 'Gaia case state and bounded rectification obligations.']],
    flow: [['OWN', 'Register the Workspace and its controller.', 'runtime'], ['AUTHORISE', 'Activate a signed Path for an actor or agent.', 'runtime'], ['COMMIT', 'Evaluate the proposal and sign the resulting Pact.', 'wallet'], ['PROVE', 'Verify evidence against the Pact and proof policy.', 'runtime'], ['SETTLE', 'Approve and broadcast the financial action.', 'network'], ['RESOLVE', 'Open a bounded exception path only when normal execution fails.', 'exception']],
    failures: [['Authority missing', 'The proposal cannot be evaluated as permitted.', 'Register or reactivate the required Workspace, Agent, and Path.'], ['Wallet action rejected', 'The Runtime state remains prepared but no financial state advances.', 'Review the exact payload and retry from the wallet boundary.'], ['Receipt cannot be verified', 'The frontend may show a submitted transaction, but settlement remains non-canonical.', 'Check chain, contract, event, status, and object binding before retrying observation.']],
    example: { title: 'One complete economic action', ...canonicalExample, steps: ['Workspace 01 owns the activity.', 'Path 04 permits prepare_railsflow up to 1,000 orUSD.', 'Proposal 018 requests 420 orUSD and receives ALLOW.', 'Pact 2048 binds the terms and evidence policy.', 'Proof verifies the opening receipt and later settlement eligibility.', 'The wallet broadcasts the Paycard and settlement transactions.', 'GIWA receipts close the canonical lifecycle.'], result: 'The same action remains traceable from delegated authority to confirmed network state.' },
    references: [{ kind: 'SYSTEM LAB', label: 'Guided proof', value: '/system', href: '/system' }, { kind: 'SOURCE', label: 'Product surface specification', value: 'docs/OPENRAILS_PRODUCT_SURFACES.md' }, { kind: 'SOURCE', label: 'Architecture', value: 'docs/GIWA_AGENT_KERNEL_ARCHITECTURE.md' }],
  },
  'why-openrails': {
    fields: [['Macro budget', 'A bounded pool separated from the owner wallet balance.'], ['Micro action', 'One exact payment intent inside the permitted budget.'], ['Velocity', 'The maximum pace at which value becomes earned or drawable.'], ['Expiry', 'The deterministic end of delegated authority.'], ['Nonce lane', 'The independent execution sequence assigned to the activity.'], ['Residual destination', 'The address or rule that receives unused value at closure.']],
    flow: [['BOUND', 'The owner defines amount, asset, duration, and counterparty scope.', 'wallet'], ['PREPARE', 'Software prepares a typed action inside those bounds.', 'runtime'], ['REVIEW', 'The wallet exposes the exact action before signing.', 'wallet'], ['EXECUTE', 'The deployed protocol opens and advances the payment object.', 'network']],
    failures: [['Broad approval exceeds commercial need', 'Software receives more practical authority than the task requires.', 'Replace it with a bounded RailsCard and exact RailsFlow.'], ['No expiry', 'Authority can outlive the activity that justified it.', 'Bind every rail or session to deterministic time limits.'], ['No residual rule', 'Unused value has no explicit close-out path.', 'Declare the residual destination before execution.']],
    example: { title: 'From wallet balance to bounded rail', context: 'The payer owns 5,000 orUSD but the activity needs only 420 orUSD for 30 seconds.', steps: ['Commit only 420 orUSD to the rail.', 'Limit earning velocity to 14 orUSD per second.', 'Isolate the flow in lane 04.', 'Return any unearned value to the payer at closure.'], result: 'The application can perform the task without receiving unrestricted access to the wallet balance.' },
    references: [{ kind: 'SYSTEM LAB', label: 'Allowed and blocked comparison', value: '/system', href: '/system' }, { kind: 'SDK', label: 'Wallet-ready drafts', value: 'sdk/src/drafts.ts' }, { kind: 'SOURCE', label: 'Trust model', value: 'docs/GIWA_AGENT_KERNEL_TRUST_MODEL.md' }],
  },
  architecture: {
    fields: [['Clients', 'System Lab, dashboard, Telegram, SDK, MCP, and REST surfaces.'], ['Runtime', 'Workspace, Path, Baphomet, Pact, Proof, and Gaia coordination.'], ['Wallet', 'Visible signing, approvals, and broadcasts controlled by the user.'], ['Protocol', 'RailsCard, RailsFlow, Paycard, Vault, and STN-Delta settlement objects.'], ['Network adapter', 'Chain identity, assets, contracts, events, and receipt verification.']],
    flow: [['REQUEST', 'A client submits an authenticated request or reads state.', 'runtime'], ['EVALUATE', 'The Runtime applies authority, policy, and object-state rules.', 'runtime'], ['AUTHORISE', 'The wallet signs the exact typed object or transaction.', 'wallet'], ['FINALISE', 'The network executes and emits canonical evidence.', 'network'], ['OBSERVE', 'The Runtime verifies the receipt and advances its matching state.', 'runtime']],
    failures: [['Client and Runtime disagree on state', 'The client may display stale or incomplete data.', 'Reload from the Kernel state and verified network observations.'], ['Runtime attempts custody', 'The trust model is violated.', 'Reject private keys and keep signing and broadcast outside the Kernel.'], ['Wrong network adapter', 'Addresses and receipts may be interpreted against the wrong deployment.', 'Bind every action and observation to explicit chain and contract configuration.']],
    example: { title: 'Telegram and web share one state model', ...canonicalExample, steps: ['Telegram prepares Proposal 018.', 'The Kernel evaluates it against Path 04.', 'The web System Lab shows the same proposal and ALLOW decision.', 'The wallet signs the Pact and GIWA transaction.', 'Both clients read the resulting canonical observation.'], result: 'Clients change interaction mode without fragmenting OpenRails state.' },
    references: [{ kind: 'SOURCE', label: 'Kernel entrypoint', value: 'agent-kernel/src/index.ts' }, { kind: 'SOURCE', label: 'Runtime implementation', value: 'agent-kernel/src/runtime.ts' }, { kind: 'SOURCE', label: 'Network configuration', value: 'sdk/src/networks.ts' }],
  },
  railscard: {
    fields: [['Owner', 'The wallet or principal granting macro authority.'], ['Asset', 'The token covered by the authority envelope.'], ['Budget', 'The maximum aggregate amount available to child flows.'], ['Committed', 'The amount already reserved by active or prepared actions.'], ['Remaining', 'Budget still available for later actions.'], ['Expiry', 'The final time at which new actions may use the envelope.'], ['Counterparty scope', 'Permitted recipients or recipient classes.']],
    flow: [['DEFINE', 'Choose asset, budget, expiry, actor, and counterparty limits.', 'runtime'], ['AUTHORISE', 'The owner signs or approves the macro envelope.', 'wallet'], ['CONSUME', 'Each RailsFlow reserves part of the remaining budget.', 'runtime'], ['RELEASE', 'Closure or cancellation returns unused authority to the envelope.', 'runtime'], ['EXPIRE', 'New child actions are rejected after the authority window ends.', 'runtime']],
    failures: [['Child allocation exceeds remaining budget', 'The RailsFlow must not be prepared or opened.', 'Reduce the allocation or close another active child flow.'], ['Asset mismatch', 'The child intent falls outside the macro envelope.', 'Prepare the flow with the authorised asset or create a separate RailsCard.'], ['Expired authority', 'No later micro action may rely on the card.', 'Create and sign a new authority envelope.']],
    example: { title: 'One budget, multiple micro actions', context: 'RailsCard 07 authorises 1,000 orUSD for a verified counterparty class.', steps: ['RailsFlow 018 reserves 420 orUSD.', 'RailsFlow 019 reserves 180 orUSD.', 'The card reports 600 committed and 400 remaining.', 'A later 500 orUSD request is rejected because only 400 remains.'], result: 'The wallet grants useful session authority while retaining a hard aggregate ceiling.' },
    references: [{ kind: 'SDK', label: 'Draft and authority helpers', value: 'sdk/src/drafts.ts' }, { kind: 'CONTRACT', label: 'Protocol authority surface', value: 'contracts/v2-factory/OpenRailsHubV2Initializable.sol' }, { kind: 'SYSTEM LAB', label: 'Macro to micro demonstration', value: '/docs/railscard', href: '/docs/railscard' }],
  },
  railsflow: {
    fields: [['Payer', 'The account funding the payment object.'], ['Recipient', 'The exact value destination.'], ['Asset', 'The settlement token and decimals.'], ['Allocation', 'The maximum amount committed to the flow.'], ['Start and expiry', 'The earning and authority horizon.'], ['Paycard ID', 'The deterministic identifier for canonical state.'], ['Lane and sequence', 'The isolated replay and ordering coordinates.'], ['Metadata hash', 'The binding to offchain commercial context.']],
    flow: [['PREPARE', 'The Runtime or SDK builds the typed intent and projected economics.', 'runtime'], ['REVIEW', 'The wallet displays payer, recipient, asset, amount, time, and binding fields.', 'wallet'], ['SIGN', 'The payer signs the exact EIP-712 intent.', 'wallet'], ['BROADCAST', 'The wallet sends the transaction to the configured network.', 'network'], ['OPEN', 'The protocol creates the Paycard and emits the opening event.', 'network'], ['OBSERVE', 'The Runtime verifies the receipt before marking the binding canonical.', 'runtime']],
    failures: [['Typed domain mismatch', 'The signature is invalid for the target chain or contract.', 'Regenerate the intent from the active network configuration.'], ['Lane or sequence reused', 'Replay or ordering checks reject the action.', 'Read the current lane state and prepare a fresh sequence.'], ['Insufficient approval or balance', 'The opening transaction reverts or cannot be submitted.', 'Fund the payer and approve the exact required amount.'], ['Wallet rejects signature', 'No Paycard opens and no value moves.', 'Leave the draft prepared and allow the user to retry.']],
    example: { title: 'Proposal 018 becomes a wallet-visible intent', ...canonicalExample, steps: ['The Runtime binds payer, recipient, 420 orUSD, lane 04, sequence 0, start, expiry, and metadata hash.', 'The wallet signs the visible payload.', 'The opening transaction creates the Paycard on GIWA.', 'The Kernel records the opening only after exact receipt verification.'], result: 'Preparation, signing, broadcast, and canonical observation remain separate and inspectable.' },
    references: [{ kind: 'SDK', label: 'RailsFlow draft', value: 'sdk/src/drafts.ts' }, { kind: 'SYSTEM LAB', label: 'Typed intent and opening', value: '/system#live-system-run', href: '/system#live-system-run' }, { kind: 'NETWORK', label: 'Current deployment', value: '/network', href: '/network' }],
  },
  'nonce-lanes': {
    fields: [['Lane', 'The vertical namespace that isolates one activity sequence.'], ['Sequence', 'The monotonically increasing horizontal position within a lane.'], ['Payer', 'The account whose replay space is being consumed.'], ['Intent hash', 'The exact action bound to the lane and sequence.'], ['Status', 'Open, used, cancelled, or otherwise unavailable.'], ['Velocity window', 'The block or time basis used for pace enforcement.']],
    flow: [['SELECT', 'Choose a lane dedicated to the activity or session.', 'runtime'], ['READ', 'Read the latest accepted sequence for that lane.', 'network'], ['SIGN', 'Bind the exact lane and next sequence into the intent.', 'wallet'], ['CONSUME', 'The contract marks the sequence used after successful execution.', 'network'], ['ADVANCE', 'The next action uses the next sequence in the same lane.', 'runtime']],
    failures: [['Sequence already consumed', 'The transaction is rejected as a replay or stale action.', 'Prepare the next sequence after reading canonical state.'], ['Wrong lane', 'The action collides with or escapes its intended activity namespace.', 'Bind the flow to the Path or session lane policy.'], ['Velocity exceeds limit', 'Execution is blocked even when the sequence is valid.', 'Wait for the pace window or reduce the requested draw.']],
    example: { title: 'Independent activities advance without blocking each other', context: 'Lane 04 carries the 420 orUSD commerce flow while lane 02 carries a separate 80 orUSD service flow.', steps: ['Lane 04 consumes sequences 0, 1, 2, and 3.', 'Lane 02 independently consumes sequences 0 and 1.', 'A delayed action in lane 04 does not stall lane 02.', 'Every signature remains bound to its exact lane and sequence.'], result: 'Parallel machine commerce gains replay protection without returning to one global sequential nonce.' },
    references: [{ kind: 'CONTRACT', label: 'Nonce enforcement', value: 'OpenRails hub execution state' }, { kind: 'SDK', label: 'Lane-aware preparation', value: 'sdk/src/drafts.ts' }, { kind: 'SYSTEM LAB', label: 'Lane 04 example', value: '/docs/nonce-lanes', href: '/docs/nonce-lanes' }],
  },
  'stn-delta': {
    fields: [['Allocated', 'The maximum value committed to the Paycard.'], ['Earned', 'The portion eligible for the recipient under the active settlement rule.'], ['Residual', 'Allocated value not earned at closure.'], ['Recipient', 'The destination for earned value.'], ['Residual destination', 'The payer or configured safe return address.'], ['Close condition', 'The time, proof, cancellation, or exception condition that triggers routing.']],
    flow: [['MEASURE', 'Determine earned value from the settlement horizon and verified state.', 'runtime'], ['CONFIRM', 'The wallet reviews the close or settlement transaction.', 'wallet'], ['ROUTE', 'The protocol sends earned value forward and residual value back.', 'network'], ['VERIFY', 'The Runtime observes exact settlement events and totals.', 'runtime']],
    failures: [['Earned value exceeds allocation', 'The accounting invariant is invalid.', 'Reject settlement and investigate the source state.'], ['Residual destination missing', 'Unused value has no safe deterministic route.', 'Require the destination before Paycard opening.'], ['Receipt totals do not match', 'The Runtime cannot mark settlement canonical.', 'Verify event values, asset decimals, and Paycard binding.']],
    example: { title: 'The 210 and 210 demonstration split', context: 'A 420 orUSD allocation reaches the midpoint of its earning horizon before settlement.', steps: ['The current demonstration calculates 210 orUSD earned.', 'The remaining 210 orUSD is residual.', 'Earned value routes to the recipient.', 'Residual value returns to the payer.'], result: 'The 210 and 210 split is an example outcome, not a fixed protocol percentage. Actual values depend on the bound earning and closure rules.' },
    references: [{ kind: 'SYSTEM LAB', label: 'Settlement economics', value: '/system#live-system-run', href: '/system#live-system-run' }, { kind: 'CONTRACT', label: 'Settlement accounting', value: 'Vault and Paycard close-out state' }, { kind: 'SOURCE', label: 'Product narrative', value: 'docs/OPENRAILS_PRODUCT_SURFACES.md' }],
  },
  paycard: {
    fields: [['Paycard ID', 'The canonical identifier for one opened payment object.'], ['Payer and recipient', 'The financial parties bound to the object.'], ['Asset and allocation', 'The token and maximum committed value.'], ['Start and expiry', 'The earning and close-out horizon.'], ['Earned and residual', 'Current accounting values.'], ['Status', 'Prepared, open, earning, settleable, settled, or terminated.'], ['Opening receipt', 'The confirmed event that proves the object exists onchain.'], ['Settlement receipt', 'The confirmed event that proves final routing.']],
    flow: [['PREPARED', 'A signed RailsFlow and required approvals are ready.', 'runtime'], ['OPEN', 'The wallet broadcasts the opening transaction.', 'network'], ['EARNING', 'Time and policy advance the eligible amount.', 'network'], ['SETTLEABLE', 'Proof and horizon conditions permit closure.', 'runtime'], ['SETTLED', 'The protocol routes earned and residual values.', 'network'], ['TERMINATED', 'No further financial transition is permitted.', 'network']],
    failures: [['Opening event missing', 'The Runtime must not claim that the Paycard exists.', 'Inspect the transaction status and exact contract logs.'], ['Proof not eligible', 'Settlement remains blocked.', 'Submit or verify the required checkpoint.'], ['Already terminated', 'A repeated settlement attempt must fail safely.', 'Treat the existing receipt as final and refresh state.']],
    example: { title: 'Canonical financial object for Pact 2048', ...canonicalExample, steps: ['The RailsFlow opening creates Paycard 018.', 'The opening receipt binds it to the payer, recipient, allocation, and Pact metadata.', 'Proof later makes it settlement eligible.', 'The settlement transaction routes earned and residual value and terminates the card.'], result: 'The Paycard is the canonical financial state, while Workspace, Path, Pact, and Proof explain its commercial context.' },
    references: [{ kind: 'NETWORK', label: 'Contract and receipt inspection', value: '/network', href: '/network' }, { kind: 'SYSTEM LAB', label: 'Opening and settlement states', value: '/system#live-system-run', href: '/system#live-system-run' }, { kind: 'CONTRACT', label: 'Paycard state', value: 'OpenRails Hub and Vault' }],
  },
  vault: {
    fields: [['Asset', 'The token held and accounted for by the deployment.'], ['Payer balance', 'Value committed or recoverable for the payer.'], ['Paycard allocation', 'Value reserved for one payment object.'], ['Earned liability', 'Value owed to the recipient under current state.'], ['Residual liability', 'Value due to the payer or configured destination.'], ['Authorised contract', 'The protocol component allowed to mutate accounting.'], ['Network address', 'The exact deployed Vault that must emit canonical evidence.']],
    flow: [['FUND', 'The payer makes value available through the supported approval or deposit path.', 'wallet'], ['RESERVE', 'Paycard opening binds part of the available value.', 'network'], ['ACCOUNT', 'The Vault tracks earned and residual liabilities.', 'network'], ['RELEASE', 'Settlement sends each liability to its destination.', 'network'], ['OBSERVE', 'The Runtime verifies exact address, event, and totals.', 'runtime']],
    failures: [['Wrong Vault address', 'A transaction may target an unrelated deployment.', 'Resolve the address only from the active network adapter.'], ['Insufficient available value', 'The Paycard cannot reserve its allocation.', 'Fund or approve the payer before opening.'], ['Accounting totals diverge', 'Canonical state cannot be reconciled.', 'Stop settlement, verify events, and preserve the failed observation.']],
    example: { title: 'Vault as custody and accounting boundary', context: 'The payer authorises 420 orUSD for Paycard 018.', steps: ['The opening transaction reserves 420 orUSD.', 'The Vault tracks the payment liability during the earning window.', 'Settlement routes the earned portion to the recipient.', 'The residual returns to the payer.'], result: 'The Runtime can explain the lifecycle without possessing custody or mutating Vault state itself.' },
    references: [{ kind: 'CONTRACT', label: 'Current Vault', value: 'deployments/giwa-sepolia.json' }, { kind: 'NETWORK', label: 'Live deployment surface', value: '/network', href: '/network' }, { kind: 'SOURCE', label: 'GIWA verification script', value: 'scripts/verify-giwa-deployment.ts' }],
  },
  'workspace-path': {
    fields: [['Workspace ID', 'The stable ownership domain for related economic activity.'], ['Controller', 'The principal authorised to change membership and authority.'], ['Members and agents', 'Human and software actors registered inside the Workspace.'], ['Path ID and revision', 'The signed, versioned authority boundary assigned to an actor.'], ['Actions', 'The operations that the Path permits.'], ['Assets and parties', 'The allowed economic scope.'], ['Ceilings', 'Per-Pact, aggregate exposure, velocity, duration, and concurrency limits.'], ['Status', 'Draft, active, suspended, revoked, or expired.']],
    flow: [['PREPARE WORKSPACE', 'Build the typed ownership registration.', 'runtime'], ['SIGN WORKSPACE', 'The controller signs the registration.', 'wallet'], ['REGISTER ACTOR', 'Add the agent or operator that may receive a Path.', 'runtime'], ['PREPARE PATH', 'Build the signed policy and economic limits.', 'runtime'], ['ACTIVATE PATH', 'Verify the controller signature and current revision.', 'runtime'], ['EVALUATE ACTIONS', 'Every proposal is checked against the active Path.', 'runtime']],
    failures: [['Workspace inactive', 'No child authority should be accepted.', 'Reactivate or create a valid ownership domain.'], ['Path revision stale', 'A proposal may rely on superseded limits.', 'Read and sign the current revision.'], ['Actor not assigned', 'The proposal has no valid delegated authority.', 'Assign and activate a Path for that actor.'], ['Ceiling exceeded', 'Baphomet returns BLOCK before Pact or wallet execution.', 'Reduce the request or authorise a revised Path.']],
    example: { title: 'Path 04 bounds the Commerce Operator', ...canonicalExample, steps: ['Workspace 01 registers the Commerce Operator agent.', 'Path 04 allows prepare_railsflow for orUSD to a verified recipient.', 'The per-Pact ceiling is 1,000 orUSD and the duration limit is 30 seconds.', 'Proposal 018 requests 420 orUSD and remains inside every rule.'], result: 'The agent can prepare a valid action without receiving owner-level wallet authority.' },
    references: [{ kind: 'KERNEL API', label: 'Prepare Workspace', value: 'POST /v1/workspaces/prepare' }, { kind: 'KERNEL API', label: 'Prepare Path', value: 'POST /v1/paths/prepare' }, { kind: 'KERNEL API', label: 'Activate Path', value: 'POST /v1/paths/activate' }],
  },
  baphomet: {
    fields: [['Proposal hash', 'The exact requested action being evaluated.'], ['Path hash', 'The exact signed authority rules used for evaluation.'], ['Workspace and actor state', 'The current ownership and actor status.'], ['Economic state', 'Current exposure, remaining budget, and concurrent activity.'], ['Result', 'Public ALLOW or BLOCK outcome.'], ['Reason codes', 'Deterministic checks that explain the outcome.'], ['Decision hash', 'The binding used by the later Pact.']],
    flow: [['SUBMIT', 'Persist the exact proposal and its context.', 'runtime'], ['LOAD', 'Resolve the active Workspace, actor, Path, and economic state.', 'runtime'], ['CHECK', 'Evaluate action, asset, counterparty, value, duration, velocity, and exposure rules.', 'runtime'], ['BIND', 'Hash the outcome to the exact proposal and Path state.', 'runtime'], ['ALLOW OR BLOCK', 'Permit Pact formation or stop the lifecycle before the wallet boundary.', 'runtime']],
    failures: [['Policy input unavailable', 'The engine cannot produce a trustworthy ALLOW.', 'Fail closed and expose the missing dependency.'], ['Proposal exceeds value ceiling', 'The result is BLOCK.', 'Reduce the amount or activate a revised Path.'], ['Economic state changed during evaluation', 'A stale decision could exceed aggregate limits.', 'Bind the state version and re-evaluate before Pact formation.']],
    example: { title: 'The strongest negative control', ...canonicalExample, steps: ['Proposal 018 requests 420 orUSD and passes every rule.', 'Baphomet returns ALLOW and Pact formation may begin.', 'Proposal 019 requests 1,420 orUSD against the same 1,000 ceiling.', 'Baphomet returns BLOCK. No Pact, wallet request, or Paycard is created.'], result: 'OpenRails proves not only that an authorised action can execute, but that an over-limit action is stopped before value movement.' },
    references: [{ kind: 'KERNEL API', label: 'Submit proposal', value: 'POST /v1/proposals' }, { kind: 'KERNEL API', label: 'Run evaluator job', value: 'POST /v1/jobs/run-next' }, { kind: 'SOURCE', label: 'Evaluator', value: 'agent-kernel/src/evaluator.ts' }],
  },
  pact: {
    fields: [['Pact ID', 'The stable commitment identifier.'], ['Proposal and decision hashes', 'The request and policy outcome that allowed formation.'], ['Parties', 'The principals bound to the commercial commitment.'], ['Terms hash', 'The exact amount, asset, recipient, duration, and related terms.'], ['Proof policy', 'The evidence required for settlement eligibility.'], ['Settlement policy', 'The permitted close and routing conditions.'], ['Exception policy', 'The bounded Gaia and rectification terms.'], ['Signatures', 'The party approvals required before activation.']],
    flow: [['DRAFT', 'Create Pact terms from an ALLOW decision.', 'runtime'], ['PREPARE SIGNATURE', 'Generate the exact typed payload for each party.', 'runtime'], ['SIGN', 'Each required party signs the same terms hash.', 'wallet'], ['ACTIVE', 'The complete signed Pact becomes the commitment of record.', 'runtime'], ['BIND SETTLEMENT', 'Link the Pact to the Paycard and opening receipt.', 'runtime'], ['CLOSE', 'Record settlement or bounded rectification outcome.', 'runtime']],
    failures: [['Decision is not ALLOW', 'A Pact must not form.', 'Return to proposal evaluation.'], ['Terms changed after one signature', 'Signatures no longer bind the same commitment.', 'Create a new Pact revision and collect fresh signatures.'], ['Required party missing', 'The Pact remains incomplete.', 'Collect the missing signature before financial preparation.'], ['Paycard binding mismatch', 'Settlement evidence cannot advance the Pact.', 'Verify metadata, Paycard ID, and opening receipt.']],
    example: { title: 'Pact 2048 freezes Proposal 018', ...canonicalExample, steps: ['The Path, proposal, and ALLOW decision hashes are included.', 'The parties sign 420 orUSD, 30 seconds, verified recipient, proof policy, and Gaia policy.', 'The opening Paycard is later bound to the same Pact metadata.', 'Settlement closes the Pact with canonical receipt evidence.'], result: 'The commercial agreement remains reconstructable independently of any frontend display.' },
    references: [{ kind: 'KERNEL API', label: 'Create from proposal', value: 'POST /v1/pacts/from-proposal' }, { kind: 'KERNEL API', label: 'Prepare party signature', value: 'POST /v1/pacts/prepare-signature' }, { kind: 'KERNEL API', label: 'Record signature', value: 'POST /v1/pacts/sign' }, { kind: 'KERNEL API', label: 'Bind Paycard', value: 'POST /v1/pacts/bind-openrails' }],
  },
  'proof-gaia': {
    fields: [['Checkpoint ID', 'The stable evidence submission identifier.'], ['Pact and Paycard binding', 'The commitment and financial object supported by the evidence.'], ['Evidence type', 'Receipt, signed claim, oracle result, service output, or other installed verifier type.'], ['Payload hash', 'The integrity binding for the evidence bundle.'], ['Verifier', 'The installed plugin or deterministic rule that evaluates it.'], ['Result', 'Approved, rejected, incomplete, or disputed.'], ['Gaia case', 'The exception record created when normal proof cannot close the Pact.'], ['Rectification obligation', 'The bounded action produced by the case determination.']],
    flow: [['SUBMIT PROOF', 'Create a signed checkpoint bound to the Pact and opening receipt.', 'runtime'], ['VERIFY', 'Run the installed plugin against source, integrity, and policy requirements.', 'runtime'], ['APPROVE', 'Mark settlement eligible when every required condition passes.', 'runtime'], ['SETTLE', 'The wallet confirms the financial close.', 'network'], ['OPEN GAIA', 'Use the exception path only for disputed or failed normal execution.', 'exception'], ['RECTIFY', 'Record the bounded obligation and canonical close-out evidence.', 'exception']],
    failures: [['Evidence source cannot be verified', 'Proof remains incomplete or rejected.', 'Provide a supported source or install the correct verifier.'], ['Evidence is not bound to the Pact', 'It cannot advance settlement eligibility.', 'Submit a checkpoint with exact Pact, Paycard, and metadata bindings.'], ['Verifier disagreement or dispute', 'Normal settlement pauses.', 'Open a Gaia case under the Pact exception policy.'], ['Rectification exceeds Pact scope', 'The determination is invalid.', 'Constrain the obligation to the previously signed exception terms.']],
    example: { title: 'Normal route and exception route', ...canonicalExample, steps: ['The opening GIWA receipt is captured and matched to Paycard 018.', 'A signed checkpoint binds the receipt to Pact 2048.', 'The verifier approves the proof and settlement becomes eligible.', 'If the receipt or service outcome is disputed, Gaia receives the same evidence history.', 'Gaia records only the bounded determination and rectification allowed by the Pact.'], result: 'Proof supports normal closure. Gaia preserves accountability when normal closure fails.' },
    references: [{ kind: 'KERNEL API', label: 'Submit checkpoint', value: 'POST /v1/checkpoints' }, { kind: 'KERNEL API', label: 'Verify checkpoint', value: 'POST /v1/checkpoints/verify' }, { kind: 'SOURCE', label: 'Plugin registry', value: 'agent-kernel/src/plugins.ts' }, { kind: 'SYSTEM LAB', label: 'Receipt proof flow', value: '/system#live-system-run', href: '/system#live-system-run' }],
  },
  'agent-kernel': {
    fields: [['Store', 'Persistent Workspace, Agent, Path, proposal, Pact, Proof, plugin, observation, and Gaia records.'], ['Typed-data builder', 'Exact wallet-readable payloads for authority and commitment signatures.'], ['Evaluator', 'Deterministic Baphomet policy and state checks.'], ['Action registry', 'Supported action definitions and required data.'], ['Plugin registry', 'Evidence verifier installation and resolution.'], ['Observer', 'Exact network, contract, event, receipt, and object binding verification.'], ['Gateway', 'Narrow authenticated interface exposed to the web product.']],
    flow: [['AUTHENTICATE', 'Verify wallet control through a signed challenge.', 'wallet'], ['PREPARE', 'Build exact typed authority or commercial objects.', 'runtime'], ['VERIFY SIGNATURE', 'Accept only signatures over the expected payload.', 'runtime'], ['EVALUATE AND PERSIST', 'Advance commercial state through typed transitions.', 'runtime'], ['OBSERVE', 'Read and verify canonical network evidence.', 'network']],
    failures: [['Private key supplied', 'The request violates the Kernel trust boundary.', 'Reject and require wallet-side signing.'], ['Mutation without authenticated session', 'The operation must not run.', 'Authenticate the address and retry the bounded request.'], ['Invalid transition', 'State remains unchanged.', 'Read the current object and use an allowed next operation.'], ['Observation from wrong contract', 'Canonical state must not advance.', 'Verify against the active network adapter and expected event.']],
    example: { title: 'Kernel coordinates without custody', ...canonicalExample, steps: ['It prepares the Workspace, Agent, Path, Pact, and checkpoint payloads.', 'The wallet signs each required authority object.', 'It evaluates Proposal 018 and persists ALLOW.', 'It never signs or broadcasts the Paycard transaction.', 'It observes the resulting GIWA receipt and records the binding.'], result: 'The backend can coordinate a real lifecycle without becoming a hot wallet.' },
    references: [{ kind: 'SOURCE', label: 'Runtime', value: 'agent-kernel/src/runtime.ts' }, { kind: 'SOURCE', label: 'HTTP server', value: 'agent-kernel/src/server.ts' }, { kind: 'SOURCE', label: 'Security policy', value: 'agent-kernel/SECURITY.md' }, { kind: 'SOURCE', label: 'Tests', value: 'agent-kernel/test/kernel.test.ts' }],
  },
  clients: {
    fields: [['System Lab', 'Guided public proof and audit surface.'], ['Personal dashboard', 'Future account-centred operational surface.'], ['Telegram', 'Conversational request and status sidecar.'], ['SDK', 'Typed application integration and wallet-ready drafts.'], ['MCP', 'Agent-readable state and safe preparation tools.'], ['REST', 'Bounded service integration.'], ['Shared state model', 'The same Workspace, Path, Pact, Proof, and settlement objects across clients.']],
    flow: [['REQUEST', 'A client prepares or requests an operation.', 'runtime'], ['READ STATE', 'The client receives the canonical commercial snapshot.', 'runtime'], ['CONFIRM', 'Financial and authority actions move to the wallet.', 'wallet'], ['REFRESH', 'Every client observes the same resulting state and receipts.', 'runtime']],
    failures: [['Client invents local canonical state', 'Surfaces disagree and auditability is lost.', 'Reload from the Kernel and verified network state.'], ['Telegram treated as custodian', 'The sidecar exceeds its intended role.', 'Keep signing and financial confirmation in the wallet.'], ['Dashboard forks object semantics', 'The product fragments by interface.', 'Reuse the shared OpenRails types and event model.']],
    example: { title: 'Telegram is one vertical', ...canonicalExample, steps: ['Telegram submits the 420 orUSD proposal.', 'The Runtime returns ALLOW.', 'The user opens the web dashboard or System Lab to inspect the full binding chain.', 'The wallet confirms the financial action.', 'Telegram and web both receive the same receipt-backed status.'], result: 'The conversational client is useful without becoming the definition of OpenRails.' },
    references: [{ kind: 'MCP', label: 'Agent tools', value: 'mcp/src/agent-tools.ts' }, { kind: 'SDK', label: 'Client exports', value: 'sdk/src/index.ts' }, { kind: 'SOURCE', label: 'Product surfaces', value: 'docs/OPENRAILS_PRODUCT_SURFACES.md' }],
  },
  'demo-walkthrough': {
    fields: [['Demo wallet', 'The connected account used for authority signatures and network transactions.'], ['Permitted proposal', '420 orUSD inside the active Path ceiling.'], ['Negative proposal', '1,420 orUSD above the same ceiling.'], ['Accelerated horizon', '30 seconds for the demonstrator.'], ['Opening receipt', 'The confirmed Paycard transaction evidence.'], ['Settlement receipt', 'The confirmed close-out evidence.'], ['Provenance', 'Demonstration, recorded, or live status for every visible claim.']],
    flow: [['CONNECT', 'Connect the demonstration wallet and correct network.', 'wallet'], ['INITIALISE', 'Sign Workspace, Agent, plugin, and Path objects.', 'wallet'], ['ALLOW ROUTE', 'Evaluate 420 orUSD, form Pact, verify Proof, open and settle.', 'network'], ['BLOCK ROUTE', 'Evaluate 1,420 orUSD and stop before Pact or wallet transaction.', 'runtime'], ['CAPTURE', 'Store real transaction hashes and receipts for recorded fallback.', 'runtime']],
    failures: [['No native gas', 'Wallet-bound transactions cannot execute.', 'Fund the demo wallet while keeping the Runtime testable up to the wallet boundary.'], ['Faucet cooldown', 'The connected account cannot claim new orUSD.', 'Use an already funded wallet or wait for eligibility.'], ['Testnet unavailable', 'A live judge run may stall.', 'Replay the previously captured real run with RECORDED provenance.']],
    example: { title: 'Acceptance definition', ...canonicalExample, steps: ['Complete one 420 orUSD lifecycle to settlement.', 'Capture opening and settlement transaction hashes.', 'Submit 1,420 orUSD and show BLOCK.', 'Confirm no Pact, wallet request, or value movement on the blocked path.'], result: 'The demonstrator proves execution, prevention, wallet separation, and canonical evidence.' },
    references: [{ kind: 'SYSTEM LAB', label: 'Run the lifecycle', value: '/system#live-system-run', href: '/system#live-system-run' }, { kind: 'NETWORK', label: 'Inspect deployment', value: '/network', href: '/network' }, { kind: 'SOURCE', label: 'Blueprint', value: 'docs/gasok-webapp-blueprint.md' }],
  },
  networks: {
    fields: [['Slug', 'Stable internal identifier such as giwa-sepolia or another configured EVM network.'], ['Display name', 'Human-readable network and environment label.'], ['Chain ID', 'The canonical EVM chain identifier.'], ['Native currency', 'The token required for transaction gas.'], ['RPC and explorer', 'Connectivity and public evidence endpoints.'], ['Settlement assets', 'Supported tokens, addresses, and decimals.'], ['Contracts', 'Factory, hub, master, Vault, faucet, and related addresses.'], ['Receipt rules', 'Expected events and confirmation requirements.']],
    flow: [['SELECT', 'Choose an explicit network adapter.', 'runtime'], ['SWITCH', 'Ask the wallet to use the matching chain.', 'wallet'], ['PREPARE', 'Build typed domains and contract calls from the adapter.', 'runtime'], ['EXECUTE', 'Broadcast only to the configured chain.', 'network'], ['VERIFY', 'Accept receipts only from configured addresses and events.', 'runtime']],
    failures: [['Wrong chain selected', 'Signatures or transactions target an unintended domain.', 'Switch before signing and regenerate the payload.'], ['Stale contract address', 'Calls and observations may target an old deployment.', 'Load addresses from the versioned deployment manifest.'], ['Missing native gas', 'The wallet cannot submit transactions.', 'Fund the wallet with testnet or production gas as appropriate.']],
    example: { title: 'One product, separate deployment evidence', context: 'The current live demonstrator uses GIWA Sepolia. Later EVM deployments use the same product surfaces.', steps: ['Keep Workspace, Path, Pact, Proof, RailsFlow, and Paycard semantics unchanged.', 'Swap chain ID, RPC, explorer, assets, contracts, and event rules through configuration.', 'Label every receipt with its actual network provenance.'], result: 'The OpenRails design and product model remain stable while each network retains exact deployment evidence.' },
    references: [{ kind: 'SOURCE', label: 'Active web adapter', value: 'apps/gasok-web/src/data/network.ts' }, { kind: 'SOURCE', label: 'SDK networks', value: 'sdk/src/networks.ts' }, { kind: 'SOURCE', label: 'GIWA deployment manifest', value: 'deployments/giwa-sepolia.json' }],
  },
  security: {
    fields: [['Runtime authority', 'Prepare, validate, persist, evaluate, and observe only.'], ['Wallet authority', 'Review, sign, approve, and broadcast.'], ['Network authority', 'Execute contracts, emit events, and confirm receipts.'], ['Session authentication', 'Proof of address control for bounded gateway operations.'], ['Replay protection', 'Typed domains, hashes, lanes, sequences, and expiry.'], ['Canonical observation', 'Exact chain, contract, event, status, and object binding checks.'], ['Provenance label', 'Demonstration, recorded, or live claim classification.']],
    flow: [['PREPARE', 'The Runtime produces an exact payload without a private key.', 'runtime'], ['REVIEW', 'The wallet exposes the action to the user.', 'wallet'], ['SIGN OR REJECT', 'The user explicitly controls progression.', 'wallet'], ['EXECUTE', 'The network enforces contract and replay rules.', 'network'], ['VERIFY', 'The Runtime accepts only exact canonical evidence.', 'runtime']],
    failures: [['Raw private key enters the Runtime', 'Custody and compromise risk increase materially.', 'Reject the input and rotate any exposed credential.'], ['Frontend claims success before receipt', 'Users may act on non-canonical state.', 'Label submitted state separately and wait for verified confirmation.'], ['Recorded run presented as live', 'Product trust and evidence integrity are undermined.', 'Use explicit RECORDED provenance and retain real hashes.'], ['Observer accepts wrong event', 'Commercial state may advance falsely.', 'Check chain, address, signature, indexed identifiers, and transaction status.']],
    example: { title: 'Visible wallet and canonical network boundary', ...canonicalExample, steps: ['The Runtime prepares Proposal 018, Pact 2048, and the RailsFlow intent.', 'The wallet separately signs authority, commitment, approval, opening, and settlement actions.', 'GIWA executes the transactions.', 'The observer verifies exact receipts before changing canonical status.'], result: 'No layer silently impersonates another, and every material handoff remains reconstructable.' },
    references: [{ kind: 'SOURCE', label: 'Kernel security policy', value: 'agent-kernel/SECURITY.md' }, { kind: 'SOURCE', label: 'Trust model', value: 'docs/GIWA_AGENT_KERNEL_TRUST_MODEL.md' }, { kind: 'SOURCE', label: 'Signature verifier', value: 'agent-kernel/src/ethersVerifier.ts' }],
  },
};
